### PR TITLE
Create calltest

### PR DESCRIPTION
**Pull request by animationzl**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[PUT ISSUE NUMBER HERE]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

### CODE REVIEW

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Build failed.

- gophercloud-unittest gophercloud-unittest : NODE_FAILURE

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Build failed.

- gophercloud-unittest gophercloud-unittest : NODE_FAILURE

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Build failed.

- gophercloud-unittest finger://allinone-zl/6adc440008dc48639cc0c9cfb6b985c3 : POST_FAILURE in 1m 30s

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Build failed.

- gophercloud-unittest finger://allinone-zl/f50342d4458e4813b6b6ed44618b29c8 : POST_FAILURE in 1m 01s

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Build failed.

- gophercloud-unittest finger://allinone-zl/8a06e22b4d5945ec8119d63624e068cd : POST_FAILURE in 1m 22s

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Build failed.

- gophercloud-unittest finger://allinone-zl/a48175b3e8bd4b4782274828ca3144b5 : POST_FAILURE in 1m 02s

**Comment by liu-sheng** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Build failed.

- gophercloud-unittest finger://allinone-zl/945bb544144944c494ca556912661b9e : POST_FAILURE in 1m 37s

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Build failed.

- gophercloud-unittest finger://allinone-zl/223f179d9350444dbdae3d94ca0c7b4f : POST_FAILURE in 1m 02s

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Unable to freeze job graph: 4444

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Unable to freeze job graph: 4444

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Unable to freeze job graph:

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Unable to freeze job graph: 4444

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
Unable to freeze job graph:

**Pull request closed without merging**
